
version: '3.8'

services:
  azure-devops-reporter:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./src:/app
      - ./logs:/app/logs
    restart: unless-stopped
